'''Crea una lista con los nombres de cinco países y muestra el tercer país de la lista.'''
'''Dada una lista de números [10, 20, 30, 40, 50], imprime el primer y el último elemento.'''
'''Crea una lista con tus comidas favoritas y muestra la segunda y la cuarta.'''
'''Dada la lista frutas = ["manzana", "banana", "pera", "uva"], cambia el segundo elemento por "naranja".'''
'''Crea una lista con cinco colores y reemplaza el último color por "negro"'''
'''Dada la lista [1, 2, 3, 4, 5], cambia el valor del tercer elemento por 100'''
'''Crea una lista vacía y agrega tres números usando .append()'''
'''Dada la lista animales = ["perro", "gato"], agrega "conejo" al final.'''
'''Crea una lista con tres deportes y añade uno más en la posición 2 usando .insert().'''
'''Dada la lista numeros = [1, 2, 3, 4, 5], elimina el primer elemento usando .pop(0).'''
'''Crea una lista con cinco frutas y elimina "pera" usando .remove().'''
'''Dada la lista [10, 20, 30, 40], borra el último elemento con .pop().'''
'''Crea una lista con cinco nombres y recórrela con un for para imprimir cada uno.'''
'''Dada la lista [2, 4, 6, 8], usa un bucle para imprimir el doble de cada número.'''
'''Crea una lista con palabras y usa un bucle para mostrar cuántas letras tiene cada palabra.'''